fruit=[]
f1=input("Enter the fruit name:")
fruit.append(f1)
f2=input("Enter the fruit name:")
fruit.append(f2)
f3=input("Enter the fruit name:")
fruit.append(f3)
f4=input("Enter the fruit name:")
fruit.append(f4)
f5=input("Enter the fruit name:")
fruit.append(f5)
print(fruit)